--- !ditz.rubyforge.org,2008-03-06/project 
name: papyrus
version: "0.3"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: papyrus
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-07-23 17:03:36.403315 Z
    - Caige Nichols <caige@sevenblend.com>
    - created
    - ""
